# Generated by Django 3.2.3 on 2021-06-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employeetable',
            },
        ),
    ]
