# Generated by Django 3.2.3 on 2021-06-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serialcrud', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serialcrud.company'),
        ),
    ]
