# Generated by Django 3.2.3 on 2021-06-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serialcrud', '0003_employeemodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='serialcrud.company'),
        ),
    ]
